pepert_ticketing_homepage:
    path:     /
    defaults: { _controller: PepertTicketingBundle:Ticketing:index }

pepert_ticketing_tickets:
    path:     /ticket/{nbTickets}
    defaults: { _controller: PepertTicketingBundle:Ticketing:ticket }
    requirements:
        nbTickets: \d+

pepert_ticketing_paiement:
    path:     /payment
    defaults: { _controller: PepertTicketingBundle:Ticketing:paiement }